### ISSUE TITLE
[Bug] Bestow Curse Concentration

### ISSUE THREAD

**Issue by MasterCroissant** [chrisk123999/chris-premades#118] opened 2023-09-15 21:33 UTC
Hello,

I've discovered that upon casting Bestow Curse at third level, the Concentration Active Effect does not recognize the spell it is supposed to be linked to:

![image](https://github.com/chrisk123999/chris-premades/assets/124537248/93c8b03e-85ed-4846-b453-5d621a70ec2b)

Which implies that when concentration is lost on the source actor, a target affected by the spell will not lose the spell effect on its Active Effect list. Not that this is a big deal, its just kind of annoying.

However, if the effect is manually deleted from the target effect list, concentration is automatically lost on the source actor.

Don't know why it does not work both ways, but it might be interesting to look into it.

I'm using v11.308 and DnD5e 2.3.1. This can be reproduced with only the required modules.

**Comment by MasterCroissant** [comment] 2023-09-16 00:14
Update: it seems there's something wrong with Midi-QOL concentration automation as of 11.0.18. This might be why I got an unlinked concentration effect. I've posted the problem on the Midi project page, so I'll keep you guys updated if anything changes.

**Comment by MotoMoto1234** [comment] 2023-09-16 10:56
The latest release of midi and dae were released right before the bossman went on a mini vacation and he had given us a warning that there was a chance some breakages would occur with effect application due to a dramatic rework.  I can't confirm/reproduce but if you are experiencing this problem, you can always step down, but if you do, go down in both midi and dae 1 major version.

**Comment by MasterCroissant** [comment] 2023-09-16 16:59
I stepped down to Midi 10.0.60 and DAE 10.0.38, even tried Midi 11.0.17 and DAE 11.0.12 for good measure and unfortunately it did not solve the issue. I might be wrong, but it seems to be directly related to the way the function for Bestow Curse triggers concentration on the source actor. Midi doesn't seem to be involved in this case, as I first thought.

**Comment by chrisk123999** [comment] 2023-09-18 21:21
Fixed in the newest update.

**Closed by chrisk123999** 2023-09-18 21:21 UTC
Labels: more information needed
