### ISSUE TITLE
Starry Form: Healing Chalice - bag

### ISSUE THREAD

**Issue by stalker168** [chrisk123999/chris-premades#137] opened 2023-10-21 16:23 UTC
The established formula in this skill @scale.circle-of-stars.starry-form[healing] + @mod - does not work correctly. This formula is rolled without dice.

The formula @scale.circle-of-stars.star + @mod works correctly. It needs to be replaced with it.

**Comment by MotoMoto1234** [comment] 2023-10-21 16:32
Are you sure this isn't just an issue where whatever way you got your subclass didn't give you the matching scale that CPR wants?

**Comment by MotoMoto1234** [comment] 2023-10-21 16:36
Yeah it would seem that you are not using DDBI and thats why your scale is wrong, here is what ddbi does:

![image](https://github.com/chrisk123999/chris-premades/assets/116308065/7d69228a-3d81-45a5-bfa9-44578d4ad164)

**Comment by stalker168** [comment] 2023-10-21 16:55
> Are you sure this isn't just an issue where whatever way you got your subclass didn't give you the matching scale that CPR wants?

Yes I am sure. With the standard formula, rolls from Healing Chalice and Archer pass without a die roll.
![image](https://github.com/chrisk123999/chris-premades/assets/31571343/dfc3861c-c2a9-4ab3-b554-8f3ec59fbbaf)

**Comment by MotoMoto1234** [comment] 2023-10-21 17:43
I'm pretty sure the issue is that you have an incorrect value set in the window I showed you in my first post.  I suspect either you don't have the scale value identifier right or the drop down where mine says DICE is set to something else for you in your subclass feature.  Or you put it on the druid item instead of the circle of stars subclass item.  This feature in CPR works totally fine if you use DDBI and follow the instructions in the CPR item in the compendium:

![image](https://github.com/chrisk123999/chris-premades/assets/116308065/c472712a-062a-40f4-94eb-c99624bc2463)

**Comment by Medianoche** [comment] 2023-10-21 18:21
**D&D Beyond** (that website from WoTC, the company we, as a united community, hate to the core and may or might not forgive in the near future) **Importer** (DDBI for shorter) is not a Required module:
[Optional supported modules](https://github.com/chrisk123999/chris-premades#optional-supported-modules).

@MotoMoto1234, hence although your reply was correct and it MIGHT fix the situation for some people, it did not resolve the underlying problem, which is that the feature "Starry Form: Healing Chalice" is not working as intended, since the variable "@scale.circle-of-stars.starry-form[healing]" is not defined and is returning a zero value, as shown on @stalker168 post.

That being said, @scale.circle-of-stars.star does not work for me and I have been forced to tamper with the module code to fix it.

**Comment by chrisk123999** [comment] 2023-10-21 18:23
A fix has been given, if you don't want to setup your scale as screenshot by Moto there's nothing else left to do.

**Closed** 2023-10-21 18:22 UTC
