### ISSUE TITLE
Summon Beast, Fey & Conjure spells won't summon: "this.hpFormula.match is not a function" + other errors

### ISSUE THREAD

**Issue by Janner3D** [chrisk123999/chris-premades#305] opened 2024-10-08 21:37 UTC
Maybe this is the case for other summon spells (might be worth checking), but I'm getting an error when Summon Fey & Beast doesn't summon the token after placing down the crosshair, and I get this error.

![image](https://github.com/user-attachments/assets/c3a3ab85-16c2-4aab-b3fd-2172bda7813d)

Foundry v12.331
DnD5e v3.3.1
Cauldron of Plentiful Resources 1.0.11
MidiQoL v 11.6.22

**Comment by Janner3D** [comment] 2024-10-08 21:42
Additionally, Conjure Animals doesn't seem to work. It gives me this when I attempt to summon:
![image](https://github.com/user-attachments/assets/d61f613b-8bf8-4106-a607-191ad9baa35f)

Conjure Fey gives me this:
![image](https://github.com/user-attachments/assets/b4a8c0d0-2251-4400-9800-a4b1ad5bd789)

**Comment by chrisk123999** [comment] 2024-10-08 21:46
Please include your full troubleshooter or join the CPR Discord for further troubleshooting. I'm unable to reproduce this issue.

**Comment by Janner3D** [comment] 2024-10-08 21:47
> Please include your full troubleshooter or join the CPR Discord for further troubleshooting. I'm unable to reproduce this issue.

[fvtt-midi-qol-troubleshooter (4).json](https://github.com/user-attachments/files/17299604/fvtt-midi-qol-troubleshooter.4.json)
Here you go! I'm on the discord under the name Janner3D

**Comment by chrisk123999** [comment] 2024-10-08 21:48
Actually, I'm able to reproduce this issue when "Mighty Summoner" is on the actor. I'll look into it.

**Comment by chrisk123999** [comment] 2024-10-08 21:53
This issue is fixed in the next update.

**Closed by chrisk123999** 2024-10-08 21:53 UTC
