### ISSUE TITLE
Shadow Blade

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [chrisk123999/chris-premades#88] opened 2023-06-25 15:14 UTC
Hi Mate. Having a problem with Automation with SB atm. When it is summoned, any attacks made in 5ft range of target rolls at disadvantage as if the shadowblade is a ranged attack. If i move the token away from the enemy, say like 10 ft, the disadvantage goes away. 

Ah i see what it is. The the "Thrown" Tag on the item that's created is interacting with Midiqol and it's giving it disadvantage.

**Comment by MotoMoto1234** [comment] 2023-06-25 15:28
Turn on attribution tooltip in the misc tab and then you can expand an attack to see the flags.  
![image](https://github.com/chrisk123999/chris-premades/assets/116308065/5fd58440-ad91-4531-a120-31de0b0a3312)

**Comment by Quinn-Aetherwood** [comment] 2023-06-25 15:35
I turned it on. It is saying DIS due to enemy being nearby, which i noticed before turning this on. The thrown tag in SB is being given DIS due to been considered a ranged weapon within threatened space.

**Comment by MotoMoto1234** [comment] 2023-06-25 15:51
Its not a ranged weapon attack but it does have a ranged weapons range.  Maybe this is a breaking change caused by the new midi optional rule.

**Comment by chrisk123999** [comment] 2023-12-06 01:53
I believe this has been fixed with newer versions of Midi-Qol. Feel free to re-open this bug report if the issue still persists.

**Closed by chrisk123999** 2023-12-06 01:53 UTC
Labels: bug
